In [36]:
# GDP Scraper
# Licensed under the MIT License. See LICENSE file for details.
from io import StringIO
import pandas as pd
import requests

In [37]:
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'\
            ' AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36'}

In [38]:
response = requests.get(url, headers=headers)
formatted_response = StringIO(response.text)
df = pd.read_html(formatted_response)

In [39]:
df

[                                                   0
 0  Largest economies in the world by GDP (nominal...,
                                                    0  \
 0  > $20 trillion $10–20 trillion $5–10 trillion ...

                                                    1  \
 0  $750 billion – $1 trillion $500–750 billion $2...

                                                    2
 0  $50–100 billion $25–50 billion $5–25 billion <...  ,
     Country/Territory IMF[1][12]            World Bank[13]             \
     Country/Territory   Forecast       Year       Estimate       Year
 0               World  115494312       2025      105435540       2023
 1       United States   30337162       2025       27360935       2023
 2               China   19534894  [n 1]2025       17794782  [n 3]2023
 3             Germany    4921563       2025        4456081       2023
 4               Japan    4389326       2025        4212945       2023
 ..                ...        ...        ...            ...        ...
 205          Kiribati        311       2024            279       2023
 206             Palau        308       2024            263       2023
 207  Marshall Islands        305       2024            284       2023
 208             Nauru        161       2024            154       2023
 209            Tuvalu         66       2024             62       2023

     United Nations[14]
               Estimate       Year
 0            100834796       2022
 1             25744100       2022
 2             17963170  [n 1]2022
 3              4076923       2022
 4              4232173       2022
 ..                 ...        ...
 205                223       2022
 206                225       2022
 207                279       2022
 208                147       2022
 209                 59       2022

 [210 rows x 7 columns],
          vteLists of countries by financial rankings  \
 0                                              Trade
 1                                         Investment
 2                                              Funds
 3                                    Budget and debt
 4                                   Income and taxes
 5                                         Bank rates
 6                                           Currency
 7                                              Other
 8  Lists of countries by GDP rankings List of int...

        vteLists of countries by financial rankings.1
 0  Account balance % of GDP Exports by product me...
 1                   FDI received past FDI abroad GFI
 2  Forex reserves Gold reserves Sovereign wealth ...
 3  Government budget PPP % of GDP per capita Cred...
 4  Wage average Disposable minimum Wage growth GN...
 5  Central bank interest rate Commercial bank pri...
 6                                     Inflation rate
 7  Financial Development Index Average annual lab...
 8  Lists of countries by GDP rankings List of int...  ,
                vteLists of countries by GDP rankings  \
 0                                            Nominal
 1                      Purchasing power parity (PPP)
 2                                         Per capita
 3                                         GDP growth
 4                        Gross national income (GNI)
 5                                Countries by region
 6                              Subnational divisions
 7  Lists of countries by financial rankings List ...

              vteLists of countries by GDP rankings.1
 0  GDP (nominal) Past and projected Sector compos...
 1  GDP (PPP) Past Past and projected Ten largest ...
 2  nominal GDP Past and projected GDP (PPP) by re...
 3  real GDP growth rate African countries Asian s...
 4  PPP per capita Nominal per capita Real income ...
 5  Africa PPP nominal Commonwealth of Nations PPP...
 6  Albania Argentina Armenia Australia Austria Ba...
 7  Lists of countries by financial rankings List ...  ,
               vteEconomic classification of countries  \
 0   Developed country Developing country Heavily i...
 1                              Three/Four-World Model
 2                        Gross domestic product (GDP)
 3                                             Nominal
 4                       Purchasing power parity (PPP)
 5                                              Income
 6                                               Wages
 7                                              Wealth
 8                             Other national accounts
 9                                   Human development
 10                                     Digital divide
 11       Net international investment position (NIIP)
 12                     Economics portal  World portal

             vteEconomic classification of countries.1
 0   Developed country Developing country Heavily i...
 1   First World Second World Third World Fourth World
 2   Nominal By country past and projected per capi...
 3   By country past and projected per capita per c...
 4   By country future estimates per capita per cap...
 5   GNI (nominal) per capita GNI (PPP) per capita ...
 6   Average wage Europe Employee compensation (per...
 7   Wealth per adult Europe Financial assets per c...
 8   Gross National Happiness Net material product ...
 9   Human Development Index by country inequality-...
 10  ICT Development Index Number of broadband Inte...
 11        Per capita (creditors) Per capita (debtors)
 12                     Economics portal  World portal  ,
                                0  \
 0                        Nominal
 1  Purchasing power parity (PPP)

                                                    1
 0  By country past and projected per capita per c...
 1  By country future estimates per capita per cap...  ]

In [40]:
df_gpd = df[2]

In [41]:
df_gpd

    Country/Territory IMF[1][12]            World Bank[13]             \
    Country/Territory   Forecast       Year       Estimate       Year
0               World  115494312       2025      105435540       2023
1       United States   30337162       2025       27360935       2023
2               China   19534894  [n 1]2025       17794782  [n 3]2023
3             Germany    4921563       2025        4456081       2023
4               Japan    4389326       2025        4212945       2023
..                ...        ...        ...            ...        ...
205          Kiribati        311       2024            279       2023
206             Palau        308       2024            263       2023
207  Marshall Islands        305       2024            284       2023
208             Nauru        161       2024            154       2023
209            Tuvalu         66       2024             62       2023

    United Nations[14]
              Estimate       Year
0            100834796       2022
1             25744100       2022
2             17963170  [n 1]2022
3              4076923       2022
4              4232173       2022
..                 ...        ...
205                223       2022
206                225       2022
207                279       2022
208                147       2022
209                 59       2022

[210 rows x 7 columns]

In [35]:
df_gpd.to_csv('list_countries_GDP.csv', encoding='utf8')